services:
  clojure:
    image: clojure:temurin-25-tools-deps
    working_dir: /app
    volumes: ["./clojure:/app", "m2-cache:/root/.m2"]
    stdin_open: true
    tty: true
    ports:
      - "127.0.0.1:12345:12345"
      - "127.0.0.1:7888:7888"

volumes:
  m2-cache:
