FROM node:22.6.0-bookworm-slim AS base
WORKDIR /usr/src/app
ARG SERVICE_NAME
ENV SERVICE_NAME=${SERVICE_NAME}

RUN \
  --mount=type=cache,target=/var/lib/apt,sharing=locked \
  --mount=type=cache,target=/var/cache/apt,sharing=locked \
  apt update && apt install --no-install-recommends -y \
    procps \
    curl \
    jq

RUN \
  --mount=type=cache,target=/root/.npm,sharing=locked \
  npm i @nestjs/cli

FROM base AS build
WORKDIR /usr/src/app

COPY ./${SERVICE_NAME} .

RUN npm install && npm run build

FROM base AS runtime
WORKDIR /usr/src/app

COPY --from=build /usr/src/app/package.json ./package.json
COPY --from=build /usr/src/app/tsconfig.json ./tsconfig.json
COPY --from=build /usr/src/app/dist ./dist
COPY --from=build /usr/src/app/node_modules ./node_modules

EXPOSE 3000
CMD ["npm", "run", "start:dev"]
